//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/zOthers/DefaultControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @DefaultControls : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @DefaultControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""DefaultControls"",
    ""maps"": [
        {
            ""name"": ""DefaultMap"",
            ""id"": ""bd47facd-02f7-487e-8ba7-46bd16d665a2"",
            ""actions"": [
                {
                    ""name"": ""OnClick"",
                    ""type"": ""Button"",
                    ""id"": ""24cbd0f4-cfbb-4d25-91f7-e5b426e1f480"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MousePosition"",
                    ""type"": ""Value"",
                    ""id"": ""f20b4e24-ec48-444c-a89c-94b2c9709d58"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""CancelOperation"",
                    ""type"": ""Button"",
                    ""id"": ""816497fc-b692-4616-a0fe-f00b687837a2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""e512fc8a-0a51-4040-a046-9d9d50bec037"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OnClick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8d74aa10-edc3-44b5-97d0-6e3a344994e6"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MousePosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f6bc0b0a-1dad-4fab-ac4f-010c9d06739f"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CancelOperation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // DefaultMap
        m_DefaultMap = asset.FindActionMap("DefaultMap", throwIfNotFound: true);
        m_DefaultMap_OnClick = m_DefaultMap.FindAction("OnClick", throwIfNotFound: true);
        m_DefaultMap_MousePosition = m_DefaultMap.FindAction("MousePosition", throwIfNotFound: true);
        m_DefaultMap_CancelOperation = m_DefaultMap.FindAction("CancelOperation", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // DefaultMap
    private readonly InputActionMap m_DefaultMap;
    private IDefaultMapActions m_DefaultMapActionsCallbackInterface;
    private readonly InputAction m_DefaultMap_OnClick;
    private readonly InputAction m_DefaultMap_MousePosition;
    private readonly InputAction m_DefaultMap_CancelOperation;
    public struct DefaultMapActions
    {
        private @DefaultControls m_Wrapper;
        public DefaultMapActions(@DefaultControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @OnClick => m_Wrapper.m_DefaultMap_OnClick;
        public InputAction @MousePosition => m_Wrapper.m_DefaultMap_MousePosition;
        public InputAction @CancelOperation => m_Wrapper.m_DefaultMap_CancelOperation;
        public InputActionMap Get() { return m_Wrapper.m_DefaultMap; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(DefaultMapActions set) { return set.Get(); }
        public void SetCallbacks(IDefaultMapActions instance)
        {
            if (m_Wrapper.m_DefaultMapActionsCallbackInterface != null)
            {
                @OnClick.started -= m_Wrapper.m_DefaultMapActionsCallbackInterface.OnOnClick;
                @OnClick.performed -= m_Wrapper.m_DefaultMapActionsCallbackInterface.OnOnClick;
                @OnClick.canceled -= m_Wrapper.m_DefaultMapActionsCallbackInterface.OnOnClick;
                @MousePosition.started -= m_Wrapper.m_DefaultMapActionsCallbackInterface.OnMousePosition;
                @MousePosition.performed -= m_Wrapper.m_DefaultMapActionsCallbackInterface.OnMousePosition;
                @MousePosition.canceled -= m_Wrapper.m_DefaultMapActionsCallbackInterface.OnMousePosition;
                @CancelOperation.started -= m_Wrapper.m_DefaultMapActionsCallbackInterface.OnCancelOperation;
                @CancelOperation.performed -= m_Wrapper.m_DefaultMapActionsCallbackInterface.OnCancelOperation;
                @CancelOperation.canceled -= m_Wrapper.m_DefaultMapActionsCallbackInterface.OnCancelOperation;
            }
            m_Wrapper.m_DefaultMapActionsCallbackInterface = instance;
            if (instance != null)
            {
                @OnClick.started += instance.OnOnClick;
                @OnClick.performed += instance.OnOnClick;
                @OnClick.canceled += instance.OnOnClick;
                @MousePosition.started += instance.OnMousePosition;
                @MousePosition.performed += instance.OnMousePosition;
                @MousePosition.canceled += instance.OnMousePosition;
                @CancelOperation.started += instance.OnCancelOperation;
                @CancelOperation.performed += instance.OnCancelOperation;
                @CancelOperation.canceled += instance.OnCancelOperation;
            }
        }
    }
    public DefaultMapActions @DefaultMap => new DefaultMapActions(this);
    public interface IDefaultMapActions
    {
        void OnOnClick(InputAction.CallbackContext context);
        void OnMousePosition(InputAction.CallbackContext context);
        void OnCancelOperation(InputAction.CallbackContext context);
    }
}
